### PR TITLE
Add support for proxy settings

### PR DESCRIPTION
**Pull request by martinskeem**
feat: add support to configure HttpClient requests with proxy settings #113
fix: InnerException referenced can be null which raises an uncaught exception and the application shuts down #114

### CODE REVIEW

**Comment by martinskeem** [comment]
Any thoughts on this? Do let me know if you have feedback

**Comment by chriswendt1** [comment]
@martinskeem Thanks for your PR!
I only reviewed the changes without testing so far, and they look good to me. I trust that you tested the proxy settings in your environment.
Only missing item I could see is a way to edit the proxy settings via command line. I try to keep parity to the GUI version. No problem, I can add that without too much effort.
I plan to accept this on Friday.

**Comment by martinskeem** [comment]
Cool, yes, I did check that the proxy settings work in our environment. I may have a different feature request / PR relating to an optional alternative location of the appsettings.json file to ease deployment in a corporate environment, but I will open a separate discussion (and PR on that if agreed)

**Comment by chriswendt1** [comment]
@martinskeem I accepted your PR squashed into one commit.
I changed the layout a bit to keep the Experimental settings at the bottom of the Settings page. 
I tested that the non-proxy functionality is not disturbed. 
**Question**: Do you rely on having a signed build published as a "Release" soon?

**Comment by martinskeem** [comment]
No, I do not, we can proceed with an unsigned build that I created and switch to the public and signed installer at a later time

**Comment by chriswendt1** [comment]
@martinskeem OK, great. Thanks.
Please submit another PR for the deployment of appsettings.json. 
I'll add the CLI functionality and then proceed to publish, maybe together with the appsettings change.

**Pull request merged**
